---
title: "Afghanistan Case Study" 
output: github_document
---

```{r setup and data visualization preferences}
library(tidyverse)
library(readxl)
library(p8105.datasets)
library(hexbin)
library(patchwork)
library(leaflet)
library(lubridate)

devtools::install_github("benmarwick/wordcountaddin",  type = "source", dependencies = TRUE)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Aidworker dataset - cleaning and tailoring
```{r basic cleaning and exploring}
aidworker_df = 
read_csv("./data/security_incidents_2020-11-25.csv") %>%
  janitor::clean_names() %>% 
  pivot_longer(
    un:other,
    names_to = "org_type", 
    values_to = "number_orgs_affected"
  ) %>% 
  select(-number_orgs_affected)

aidworker_df$date <- as.Date(with(aidworker_df, paste(year, month, day, sep = "-")), "%Y-%m-%d")

afghan_aidw_df = 
aidworker_df %>% 
  filter(country == "Afghanistan") %>% 
  filter(year %in% c("2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016")) 


# tried to write a function, didn't work. Tried to group by and summarize, didn't work. Tried to mutate and create a new column for totals but that somehow didn't work either. Also tried to recode the columns, and you guessed it - that didn't work. Had to do it like this, but it's not even remotely efficient, and it isn't in a dataframe translatable to an image, so if someone has a better way, please feel free to overwrite this. 


afghan_aidw_df %>% 
   filter(year %in% c("2008")) %>% 
  count(internationals_killed)

afghan_aidw_df %>% 
   filter(year %in% c("2008")) %>% 
  count(nationals_killed)

afghan_aidw_df %>% 
   filter(year %in% c("2009")) %>% 
  count(internationals_killed)

afghan_aidw_df %>% 
   filter(year %in% c("2009")) %>% 
  count(nationals_killed)

afghan_aidw_df %>% 
   filter(year %in% c("2010")) %>% 
  count(internationals_killed)

afghan_aidw_df %>% 
   filter(year %in% c("2010")) %>% 
  count(nationals_killed)

afghan_aidw_df %>% 
   filter(year %in% c("2011")) %>% 
  count(internationals_killed)

afghan_aidw_df %>% 
   filter(year %in% c("2011")) %>% 
  count(nationals_killed)

afghan_aidw_df %>% 
   filter(year %in% c("2012")) %>% 
  count(internationals_killed)

afghan_aidw_df %>% 
   filter(year %in% c("2012")) %>% 
  count(nationals_killed)

afghan_aidw_df %>% 
   filter(year %in% c("2013")) %>% 
  count(internationals_killed)

afghan_aidw_df %>% 
   filter(year %in% c("2013")) %>% 
  count(nationals_killed)

afghan_aidw_df %>% 
   filter(year %in% c("2014")) %>% 
  count(internationals_killed)

afghan_aidw_df %>% 
   filter(year %in% c("2014")) %>% 
  count(nationals_killed)

afghan_aidw_df %>% 
   filter(year %in% c("2015")) %>% 
  count(internationals_killed)

afghan_aidw_df %>% 
   filter(year %in% c("2015")) %>% 
  count(nationals_killed)

afghan_aidw_df %>% 
   filter(year %in% c("2016")) %>% 
  count(internationals_killed)

afghan_aidw_df %>% 
   filter(year %in% c("2016")) %>% 
  count(nationals_killed)

```


```{r}
#alisha, wondering if this would work... making two dfs one with a new var 'internationals_killed_tot' and another 'nationals_killed_tot' and then merging the datasets? I am not sure why it is making so many rows for each year? Kailey - there are multiple because it records aid workers from different organizations as separate datapoints? I'm a little confused with what to do about this data, but im going to try condensing it. 

afghan_aidw_international_df = 
aidworker_df %>% 
  filter(country == "Afghanistan") %>% 
  filter(year %in% c("2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016")) %>% 
  group_by(year) %>% 
  count(internationals_killed) %>% 
  mutate(
    internationals_killed_tot = n
  )

afghan_aidw_national_df = 
aidworker_df %>% 
  filter(country == "Afghanistan") %>% 
  filter(year %in% c("2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016")) %>%
  group_by(year) %>%
  count(nationals_killed) %>% 
  mutate(
    nationals_killed_tot = n
  ) 

afghan_aidw_df_new = 
  left_join(afghan_aidw_international_df, afghan_aidw_national_df, by = "year") %>% 
  select(year, internationals_killed_tot, nationals_killed_tot) %>% 
  group_by(year) %>% 
  mutate(
    yearly_internationals_killed = sum(internationals_killed_tot),
    yearly_nationals_killed = sum(nationals_killed_tot)) %>% 
  select(year, yearly_internationals_killed, yearly_nationals_killed) %>% 
  slice(1, 16, 28, 40, 50, 54, 68, 86, 93)

# %>%  
  # aggregate(cbind(deaths_civilians, deaths_unknown) ~ year, sum) %>% view()
  # this line of code isn't working (and nothing similar will work) because R is not recognizing "year" as a list - does anyone have another way of aggregating the data by year?

#UPDATE:alisha, i think this works!! it might not be 100% the right way to do it but it sums up per year! 

afghan_aidw_df_new %>% 
     ggplot(aes(x = year, y = yearly_internationals_killed, col = "International")) +
   geom_line() +
  geom_line(aes(x = year, y = yearly_nationals_killed, col = "National")) +
  labs(
    title = "Number of Aidworkers Killed By Origin (National vs. International)",
    x = "Year",
    y = "Number Killed"
  ) 
```

Uppsala data upload and cleaning/tailoring (downloaded data for Afghanistan only)

```{r}
#Looking at deaths among all civilians verses all aidworkers side by side

#Aidworkers: 
aidw_killed_df =   
afghan_aidw_df %>% 
  group_by(year) %>% 
  count(total_killed) %>%
  select(year, n) %>% 
  mutate(
    aidwk_killed = sum(n)) %>% 
  select(year, aidwk_killed) %>% 
  slice(1, 7, 11, 16, 21, 23, 30, 36, 43)


#All civilians: I am a bit confused on who each death represents - deaths_a and deaths_b represent each side of the conflict. Because this is different for each instance, it might be best to take it out and just focus on civilian deaths - removing unknown deaths here for that purpose)

afghan_upp_df = 
read_csv("./data/afghanistan_uppsala.csv") %>%
  janitor::clean_names() %>% 
  filter(year %in% c("2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016")) %>% 
  select(year, deaths_civilians) %>% 
  group_by(year) %>% 
  count(deaths_civilians) %>% 
  mutate(
    civilian_deaths = sum(n)
  ) %>% 
  select(year, civilian_deaths) %>% 
  slice(1, 19, 39, 63, 84, 104, 123, 143, 164) 

##alisha, this slice function is creating doubles for 2009 onward... i tried slicing again and taking the first of each double and got the same thing returned... very confused 

afghan_upp_df %>% 
  ggplot(aes(x = year, y = deaths_civilians, col = "Civilian")) +
   geom_line() +
  geom_line(data = aidw_killed_df, aes(x = year, y = aidwk_killed, col = "Aidworker")) +
  labs(
    title = "Aidowrkers and Civilians Killed",
    x = "Year",
    y = "Number Killed"
  ) 
```

