---
title: "Patterns in Aid Worker Attacks over Time"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(plotly)
library(viridis)
library(tidyverse)
library(shiny)
library(xml2)
library(rvest)
```

```{r loading and tidying data }
url = "https://aidworkersecurity.org/incidents/search"
aidworker_html = read_html(url)

aidworker_df = 
  aidworker_html %>% 
  html_nodes(css = "table") %>%  
  first() %>% 
  html_table() %>% 
  as_tibble()

aidworker_df =
  aidworker_df %>%
  janitor::clean_names() %>% 
  drop_na(location) %>% 
  select(-source, -verified) %>% 
  rename(year = year_sort_descending) %>% 
  mutate(intl_org_affected = 
           case_when(
             un != 0 ~ "yes",
             ingo != 0 ~ "yes",
             icrc != 0 ~ "yes",
             ifrc != 0 ~ "yes",
             other != 0 ~ "yes",
             lngo_and_nrcs != 0 ~ "no"),
         intl_org_affected = as.factor(intl_org_affected)) %>% 
  relocate(id, month, day, year, country, intl_org_affected)

empty_as_na <- function(x){
    if("factor" %in% class(x)) x <- as.character(x) 
    ifelse(as.character(x)!="", x, NA)
}

aidworker_df = 
aidworker_df %>% mutate_each(funs(empty_as_na))

aidworker_df = 
  mutate(aidworker_df, 
         attack_abr = case_when(
           means_of_attack == "Kidnap-killing" ~ "Kidnapping",
           means_of_attack == "Kidnapping" ~ "Kidnapping",
           means_of_attack == "Body-borne IED" ~ "IED", 
           means_of_attack == "Vehicle-born IED" ~ "IED", 
           means_of_attack == "Roadside IED" ~ "IED",
           means_of_attack == "Landmine" ~ "Explosives", 
           means_of_attack == "Shelling" ~ "Explosives",
           means_of_attack == "Other Explosives" ~ "Explosives",
           means_of_attack == "Aerial bombardment" ~ "Explosives",
           means_of_attack == "Rape/sexual assault" ~ "Rape/sexual assault",
           means_of_attack == "Complex attack" ~ "Complex attack",
           means_of_attack == "Shooting" ~ "Shooting",
           means_of_attack == "Unknown" ~ "Unknown", 
           means_of_attack == "Bodily assault" ~ "Bodily assault"
           ))

## dataframe for all aid worker attacks 

all_attacks = 
aidworker_df %>% 
  drop_na(year) %>% 
  select(id, year, country, total_national_staff, means_of_attack, attack_context, intl_org_affected, location, attack_abr) %>% 
  as_tibble() %>% 
  group_by(means_of_attack)

## dataframe for plot of national aid worker attacks 

natl_attacks = 
  aidworker_df %>% 
  select(id, year, country, total_national_staff, attack_abr, attack_context, intl_org_affected, location) %>% 
  drop_na(year) %>% 
  as_tibble()

## dataframe for plot of international aid worker attacks 

intl_attacks = 
aidworker_df %>% 
    drop_na(year) %>%
       drop_na(location) %>% 
  select(id, year, country, total_international_staff, means_of_attack, attack_context, intl_org_affected, location, attack_abr) %>% 
    as_tibble() 


```

Attacks on Aid Workers Over Time 
==================================================

Column  {.sidebar}
-----------------------------------------------------------------------



The plot on the right outlines types of attacks among all aid workers affected by violence. 

How have attacks on aid workers changed over time? Do means of attack (IED, sexual assault, kidnapping, etc.) change based on the context, location, and type of organization (international vs. national)? 

Move the sliders to explore patterns over time.

```{r}

## pull location of attack 
loc_attack = aidworker_df %>% distinct(location) %>% pull()


## create radio buttons input 
radioButtons(
  "location_choice",
  label = h3("Select Attack Location"),
  choices = loc_attack, selected = "Road"
)

## Year slider function 
years = aidworker_df %>% distinct(year) %>% pull()

sliderInput(
  "years_choice",
  label = h3("Select Date Range"),  1997, 2020, value = c(2015, 2019), step = NULL, round = FALSE, ticks = TRUE, animate = FALSE, sep = "")

## Type of Organization Affected 
org_type = aidworker_df %>% distinct(intl_org_affected) %>% pull()

checkboxGroupInput("org_choice", 
                   label = h3("International Organization Affected?"),
                   choices = org_type, selected = "Yes")
```


Column {tabset}
-----------------------------------------------------------------------

### All Attacks against Aid Workers 

```{r}


renderPlotly({ 
  
all_attacks_plot = 
  all_attacks %>%
    filter(
      location == input[["location_choice"]],
      year == input[["years_choice"]],
      intl_org_affected == input[["org_choice"]])

all_attacks_plot %>% 
  plot_ly(x = ~year, y = ~number_attack, type = "scatter", mode = "markers", alpha = 0.5, color = ~means_of_attack, text = ~text_label)
 
})


```

Attacks by Worker Nationality 
=========================================

Column  {.sidebar}
-----------------------------------------------------------------------


These plots highlight differences in attacks among national and international staff of aid organizations. 

How have attacks on aid workers changed over time? Do means of attack (IED, sexual assault, kidnapping, etc.) change based on the context, location, and type of organization (international vs. national)? 
  
Move the sliders to explore patterns over time.

```{r}


## pull location of attack 
loc_attack = aidworker_df %>% distinct(location) %>% pull()


## create radio buttons input 
radioButtons(
  "location_choice",
  label = h3("Select Attack Location"),
  choices = loc_attack, selected = "Road"
)

## Type of Organization Affected 
org_type = aidworker_df %>% distinct(intl_org_affected) %>% pull()

checkboxGroupInput("org_choice", 
                   label = h3("International Organization Affected?"),
                   choices = org_type, selected = "Yes")

## Year slider function 
years = aidworker_df %>% distinct(year) %>% pull()

sliderInput(
  "years_choice",
  label = h3("Select Date Range"),  1997, 2020, value = c(2015, 2019), step = NULL, round = FALSE, ticks = TRUE, animate = FALSE, sep = "")

```

Column {.tabset}
-----------------------------------------------------------------------

### National Aid Worker Incidents 

```{r}

renderPlotly({ 
  natl_attacks %>%
  mutate(text_label = str_c("Country: ", country, '\nAttack Context: ', attack_context)) %>% 
  plot_ly(
    x = ~year, y = ~total_national_staff, type = "scatter", mode = "line",
    alpha = 0.5, color = ~attack_abr, text = ~text_label)
})

```

### International Aid Worker Incidents 

```{r}

renderPlotly({ 
  intl_attacks %>%
    mutate(text_label = str_c("Country: ", country, '\nAttack Context:', attack_context)) %>% 
  plot_ly(
    x = ~year, y = ~total_international_staff, type = "scatter", mode = "lines",
    alpha = 0.5, color = ~attack_abr, text = ~text_label)
})

```
