---
title: "Map of Aid Worker Attacks"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
runtime: shiny
---

```{r setup, include = FALSE}
library(tidyverse)
library(dplyr)
library(leaflet)
library(lubridate)
library(rvest)
library(httr)
library(flexdashboard)
library(plotly)
library(viridis)
library(stringr)
library(rworldmap)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

## Data import and tidying

url = "https://aidworkersecurity.org/incidents/search"
aidworker_html = read_html(url)

aidworker_df = 
  aidworker_html %>% 
  html_nodes(css = "table") %>%  
  first() %>% 
  html_table() %>% 
  as_tibble()

aidworker_df =
  aidworker_df %>%
  janitor::clean_names() %>% 
  select(-source, -verified) %>% 
  rename(year = year_sort_descending) %>% 
  mutate(intl_org_affected = 
           case_when(
             un != 0 ~ "yes",
             ingo != 0 ~ "yes",
             icrc != 0 ~ "yes",
             ifrc != 0 ~ "yes",
             other != 0 ~ "yes",
             lngo_and_nrcs != 0 ~ "no"),
         intl_org_affected = as.factor(intl_org_affected)) %>% 
  mutate(
    latitude = as.numeric(latitude),
    longitude = as.numeric(longitude)
    ) %>% 
  relocate(id, month, day, year, country, intl_org_affected)

empty_as_na <- function(x){
    if("factor" %in% class(x)) x <- as.character(x) 
    ifelse(as.character(x) != "", x, NA)
}

aidworker_df = 
aidworker_df %>% mutate_each(funs(empty_as_na)) 

## Aggregated data per country, year

global_map_df = 
  aidworker_df %>% 
  mutate(
    kidnapping = case_when(means_of_attack %in% c("Kidnapping", "Kidnap-killing") ~ 1),
    shooting = case_when(means_of_attack %in% c("Shooting") ~ 1),
    assault = case_when(means_of_attack %in% c("Bodily assault", "Rape/sexual assault") ~ 1),
    explosive = case_when(means_of_attack %in% c("Aerial bombardment", "Landmine", "Other Explosives", "Roadside IED",
                                                 "Shelling", "Vehicle-born IED") ~ 1)) %>% 
  drop_na(year) %>% 
  group_by(country, year) %>% 
  summarize(
            number_incidents = n(),
            tot_national = sum(total_national_staff),
            tot_intl = sum(total_international_staff),
            tot_victims = sum(total_victims),
            tot_kidnappings = sum(kidnapping, na.rm = TRUE),
            tot_shootings = sum(shooting, na.rm = TRUE),
            tot_assault = sum(assault, na.rm = TRUE),
            tot_explosive = sum(explosive, na.rm = TRUE)) %>% 
  drop_na(country)

global_map_df$country =
  recode(global_map_df$country,
         'Central African Republic' = 'Central African Rep.',
         'Republic of Congo' = 'Congo',
         'Cote D\'Ivoire' = 'Côte d\'Ivoire',
         'Democratic Republic of the Congo' = 'Dem. Rep. Congo',
         'Occupied Palestinian Territory' = 'Palestine',
         'South Sudan' = 'S. Sudan',
         'Syrian Arab Republic' = 'Syria',
         'Western Sahara' = 'W. Sahara'
         )

global_map_df =
  global_map_df %>% 
  filter(country != "Mauritius") %>% 
  rename(name = country)

## read in polygon data

countries = geojsonio::geojson_read("./data/custom.geo.json", what = "sp")

```

Column {.sidebar}
-----------------------------------------------------------------------

This map shows the number of incidents in each country, from the Aid Worker Security Database, since 1997. Move the slider to adjust the year. Hover over each country to see more details about attacks in each country for a given year. 

```{r input_panel}
inputPanel(
 sliderInput("year",
             label = "Year",
              min = 1997,
             max = 2020,
             value = 1,
             sep = "")
  )
```

Column 
-----------------------------------------------------------------------

### GLOBAL MAP

```{r global_map, echo=FALSE}

map_data = 
  reactive({
    victim_year_df = global_map_df %>%
    filter(year == input$year)

  sp::merge(countries, victim_year_df)

  })

renderLeaflet({
  
  bins = c(0, 5, 10, 20, 50, 100, 200)
  
  pal = colorBin("YlOrRd", domain = map_data()$tot_victims, bins = bins)

  labels = glue::glue("<strong>{map_data()$name}</strong><br/>Total Incidents: {map_data()$number_incidents}<br/>Total Victims: {map_data()$tot_victims}<br/>National Victims: {map_data()$tot_national} <br/>International Victims: {map_data()$tot_intl}") %>%
  purrr::map(htmltools::HTML)
  
  map_data() %>%
  leaflet() %>%
  addTiles() %>% 
  addPolygons(
    fillColor = ~pal(tot_victims),
    weight = 2,
    opacity = 1,
    color = "black",
    dashArray = "1",
    fillOpacity = 0.5,
    highlightOptions = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto")) %>%
  addLegend(pal = pal, values = ~tot_victims, opacity = 0.7, title = NULL,
    position = "bottomright"
    )
})

```

Note that data from Mauritius is excluded due to the content of the underlying map. Our dataset includes one incident in Mauritius in 2017, an assault with one national victim.