---
title: "plotly examples"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: flatly
---

# examples of plotly

We're going to look at NYC Airbnb data.

```{r}
library("p8105.datasets")
library("tidyverse")
library("plotly")
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>% 
  select(neighbourhood_group, neighbourhood, rating, price, lat, long, room_type) %>% 
  filter(
    neighbourhood_group == "Manhattan",
    price %in% 100:500,
    room_type == "Entire home/apt"
  ) %>% 
  drop_na(rating)
```

# Plotly plots

## scatterplot

```{r}
nyc_airbnb %>% 
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) %>% 
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_label, alpha = .5,
          type = "scatter", mode = "markers")
```

## boxplot

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, x = ~neighbourhood, color = ~neighbourhood,
          type = "box", colors = "viridis")
```


## bar plot
```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, colors = "viridis", type = "bar")
```

# ggplotly creates something that looks like ggplot but is interactive like plotly
```{r}
ggp_scatter = 
  nyc_airbnb %>% 
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point()

ggplotly(ggp_scatter)
```

```{r}

```

