---
title: "Project Report"
author: "Natalie Boychuk, Alisha Sarakki, Brennan Bollman, Emily Bamforth, Kailey Rishovd"
date: '`r format(Sys.time(), "%y-%m-%d")`'
output: github_document
---

# P8105 Final Project Repot 

# Title: "Attacks on Aid: Quantifying Risk of Violence among Aid Workers in Global Humanitarian Settings" 

*NOTES* 

* Should discuss process in detail, using code chunks and in-line code, as well as the logic for code
* Should be transparent about any challenges encountered, changes in approaches, etc. describe efforts that fail as well as what worked?
* Should be a standalone document that fully describes the project process and results. 
* 'Write high quality code that's understandable to outside reader' - should review collaborative code to make as tidy as possible

* Question: not sure if this should be a Rmd or pdf??

## Project Motivation

In recent decades, attacks on aid workers in complex crises have been steadily increasing, with 483 workers killed, kidnapped, or wounded in 2019. We are interested in understanding changes in the risk associated with humanitarian action in different geographic contexts and over time. We plan to focus our analysis around the Aid Worker Security Database (AWSD, via Humanitarian Outcomes organization): which has collected data on attacks against humanitarian aid workers globally since 1997. We will merge this with other data on violent attacks in conflict settings via the Safeguarding Health in Conflict Coalition (SHCC) and Uppsala Conflict Data Program (UCDP) to assess the relationship between aid worker attacks and conflict intensity, conflict actors (state vs. non-state actors), and aid worker characteristics (national vs. international, type of organization). We may then focus  on one or more key settings/case study countries and analyze these contexts with regard to the degree of humanitarian organizations’ operational presence, and other possible indicators of insecurity (GDP/capita, food prices, population displacement, natural disaster etc). 

### Related work

* anything else that inspired us, from an analysis or methodological pov etc: a paper, website, something we discussed in class.

## Initial questions

* What questions were we trying to answer?

* How did these questions evolve over the course of the project?

* What new questions did we consider in the course of our analysis?

## Data 

* Data sources: process of data collection

* Scraping method: Brennan pulled csv's initially, may need to do this in a way that involves data scraping.

* Data cleaning -- show code and describe logic

* Joining data sets, and different uses of different data sets

## Exploratory analysis

*HERE WE NEED TO ACTUALLY PRESENT ANY OF OUR RELEVANT EDA AND VISUALIZATIONS*

* Present EDA, visualizations, summaries, *exploratory statistical analysis*

* Justify the steps we took

* Show any major changes to our ideas

* This sounds like a combined methodology and results section. Will need subsections.

## Additional analyses

* Describe in detail any formal statistical analyses (regression etc)

## Discussion

* What were our findings? 

* Were they what we expect?

* What insights into the data can we make?

* Suggestions for further research and analysis of this topic?

