---
title: "Tasks to do"
author: "Natalie Boychuk, Alisha Sarakki, Brennan Bollman, Emily Bamforth, Kailey Rishovd"
date: '`r format(Sys.time(), "%y-%m-%d")`'
output: github_document
---

# P8105 Final Project 

## Title: "Attacks on Aid: Quantifying Risk of Violence among Aid Workers in Global Humanitarian Settings" 



## MEETING NOV 30: Team members and task assignments

### Natalie

* Will work on dashboard of attack context 

* Regression starting

### Emily

* Map to see how much data there is: density of attacks over time with heatmap? Questions to use each GPS location or use? Or by country (center GPS coord of each country that becomes dropdown) that aggregates over year (changing heatmap over time)
Dropdown to filter by: year, international_victims, national_victims, total_victims, means_of_attack, attack_context? Or just look at total victims?


### Kailey

* Make new df for Afghanistan data using the 'section 1' code: reading aidworker_df from web, and then filter by country (completed)

* Check numbers to make sure the aidworker_df filtered for afghanistan numbers of aidworkers affected (international & national) make sense? (completed)

* Work on Afghanistan case study more qualitatively: visualize Uppsala df stuff


### Alisha

* Work on the Afghanistan case study more qualitatively

### Brennan

* Manipulate aid worker dataframe so that all blanks are NA missing values. 

* Explain process of data cleaning and unknowns as having meaning. 

* Collapse variables of means_of_attack.

* Make a regional variable for Natalie's dashboard

* Show basic static EDAs: 
-static line graph of attacks over year in most deadly countries

* Help with regression

* Report


--------------------


## Datasets

#### Uppsala

Uppsala GED: all georeferenced data of armed conflict from 1989. An incident where armed force used by one organized actor against another organized actor or civilian resulting in at least one death.
Codebook: https://ucdp.uu.se/downloads/ged/ged201.pdf 


Humanitarian data: operational datasets of how many orgs work in country?

#### Aid workers

#### SHCC 
(Afghanistan only? iterate multiple years)


## Questions

* Do aid worker violence correlate with higher overall violence?

* How has pattern of aid worker violence changed over time: nationals vs international attacks, type of attack, etc? 


### Aidworker dataset - Natalie, Emily, Brennan

* Over time and countries, are there patterns to show differences in aidworker attacks? (maybe shiny plot)

* Different types of org workers attacked more frequently (UN vs INGO vs local NGOs)

* Are attacks against international aid workers different versus national aid workers? Has the proportion of attacks on international vs national aid workers changed over time.
 * stat test on this?

* Is kidnapping more common among international aid workers versus national aid workers?

* Have types of attacks changed over time?

* Some sort of map with lat/long: leaflet or shiny?

* EDA: attack context, type of attack, actor type 

* Aid worker interactive map:
** Include dropdown / hover over link to show major events. 
** Highlight countries with attacks but no major events, or protracted conflicts: CAR, Nigeria, DRC? 

* Logistic regression: probability experiencing attack with IVs of type NGO, national/international, context of attack, type of attack, actor type
 

### Focus on afghanistan - explain why we chose this one. Use multiple datasets. - Alisha, Kailey, Brennan

Use years 2008 - 2016 (describe why in report and show code)

1. Overall violence - Uppsala GED201 (?)
2. Aid worker violence
3. Health facility attacks - SHCC 

Step 1: read in, tidy and filter datasets


* Filter Uppsala dataset just for this country to examine overall violence overtime alongside violence against aidworkers. 

* Deaths among all civilians versus all aidworkers side by side

* SHCC Afghanistan dataset - would have to bring in multiple years.

* Discuss confounders (U.S. administration changes? Troop levels in country? Natural disaster?)


### Website 



### TABLE -- Aidworker joined with Uppsala

* Join aidworker and Uppsala based on country & date.



## Intended Final Products 

* EDA & visualization on aid worker attacks: increasing over time? Proportion of ‘national’ versus international worker attack? Type of attacks?

* Global map of “hotspots” of aid worker attacks by type (kidnapping, landmine, etc.) - multiple years, likely using Leaflet

* Shiny map interactive map for one year of data with dropdown menu showing different outcomes per country: aid worker attacks, health facility attacks, civilian casualties, displacement, etc.

* Interactive app with a predictive model for attack risk based on the worker’s nationality, the country in which they work, type of conflict, number civilians killed in that conflict, and other predictive factors (this will involve regression analysis)
  * We are open to suggestions from the teaching team as to whether this task would be feasible/valid, given that it may be difficult to determine all relevant predictors in the project time period. 


*Visualizations*: potential challenges in mapping attack data given different geographic variables across datasets (latitutde vs. longitude, city or neighborhood level)

*Analyses*: there may be insufficient number of attacks in each country context over time to meaningfully assess differences between countries. 
  * Any predictive models would not be able to take into consideration behavioral factors of aid workers that may influence violence, but will still allow us to examine risk factors. Similarly, the predictive model cannot predict political/civil unrest, natural disasters, resource shortages, etc. but will be able to calculate risk using these as risk factors. 

*Coding*: 


  * Worldwide data may be large and unwieldy and also have multiple years of data (though aid worker attacks relatively few per country per year) - will need to do EDA to decide whether to subset certain # of years.
  * Multiple datasets: we will at least need to combine aid worker security database with Uppsala datasets on total / civilian casualties by country etc which might be tedious.
  * Regression analysis may require literature review and other considerations to determine if statistically valid, and also would combine indicators from multiple datasets. 
  * Consideration of doing both global analysis and ‘zero-in’ on one or two key contexts to do more granular analysis. Decision about which portion of analysis should be global and which context specific pending EDA.



